Set up database
collaboration-inc/movie-seller pull request #14
Opened 2021-01-27 12:17 UTC by kenash-dev

Add dbup project to the solution.
create appsetting.json for the project.
add a test script to create a table in database.

2021-01-28 00:51 UTC, mtran45 requested changes

2021-01-28 00:51 UTC, mtran45 commented on src/MovieSeller.sln
> +<<<<<<< HEAD
Remove merge conflict

2021-01-28 00:51 UTC, mtran45 commented on src/MovieSellerDb/Program.cs
> +            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
Indent these lines startin with .

2021-01-28 00:51 UTC, mtran45 commented on src/MovieSellerDb/Scripts/001-CreateDatabase.sql
> +	[Id] INT NOT NULL PRIMARY KEY,
```suggestion
	[Id] INT IDENTITY NOT NULL PRIMARY KEY, 
```

2021-01-28 00:51 UTC, mtran45 commented on src/MovieSellerDb/appsettings.json
> +{
Hmm I want to make a comment on this file and not a specific line. It's possible in Bitbucket but not sure if you can do it in Github..

Anyway, my comment:
This should probably be a template file without anything in the connection strings. And then the dev database connection string will be specified in appsettings.Development.json

But we can sort that out later I suppose

2021-01-28 00:51 UTC, mtran45 commented on src/MovieSellerDb/appsettings.json
> +
Remove empty line

2021-02-02 03:01 UTC, kenash-dev commented on src/MovieSellerDb/Scripts/001-CreateDatabase.sql
> +	[Id] INT NOT NULL PRIMARY KEY,
done

2021-02-02 03:02 UTC, kenash-dev commented on src/MovieSellerDb/appsettings.json
> +
Not an empty line, it's a new line, probably webviewer is showing more space, check in  your VS once before approving.

2021-02-02 12:52 UTC, mtran45 approved these changes

2021-02-02 13:06 UTC, merged